# Generated by Django 5.2.3 on 2025-07-25 20:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_journal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
