# Generated by Django 5.2.3 on 2025-07-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_journal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
