# Generated by Django 5.2.3 on 2025-07-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_journal_date'),
        ('journal', '0004_journal_ai_analysis'),
    ]

    operations = [
    ]
