# Generated by Django 5.2.3 on 2025-07-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_merge_20250726_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='ai_analysis',
            new_name='ai_insight',
        ),
    ]
