# Generated by Django 5.2.3 on 2025-07-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_rename_ai_analysis_journal_ai_insight'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='joy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='neutral',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='sad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='ai_insight',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
