# Generated by Django 5.2.3 on 2025-07-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_added',
            new_name='date_created',
        ),
    ]
